name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # My github token : add more options needed
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          config_order : languages, stars
          config_timezone : Asia/Seoul
          
          #Starred topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          
          #language activity
          plugin_languages: yes
          
          
